name: example-environmen

dependencies:
  - python=3.6
  - Cython
  - numpy
  - scipy
  - matplotlib
  - astropy
  - python-graphviz
  - scikit-learn
  - jupyter
  - notebook
  - pip:
      - corner
      - treeinterpreter
